vim.g.mapleader = ' '
vim.g.maplocalleader = ','

vim.keymap.set('t', '<ESC>', '<C-\\><C-n>', {})
vim.keymap.set('', 'w', function() require('spider').motion('w') end, {})
vim.keymap.set('', 'e', function() require('spider').motion('e') end, {})
vim.keymap.set('', 'b', function() require('spider').motion('b') end, {})
vim.keymap.set('', 'ge', function() require('spider').motion('ge') end, {})
vim.keymap.set('', ' ', '<Nop>', { silent = true })
vim.keymap.set('', '<leader>f', '', { desc = 'File' })
vim.keymap.set('', '<leader>fs', '<CMD>w<CR>', { desc = 'Save file' })
vim.keymap.set('', '<leader>ff', function() require('fzf-lua').files() end, { desc = 'Find file' })
vim.keymap.set('', '<leader>q', '', { desc = 'Quit/Session' })
vim.keymap.set('', '<leader>qq', '<CMD>qa<CR>', { desc = 'quit' })
vim.keymap.set('', '<leader>b', '', { desc = 'Buffer' })
vim.keymap.set('', '<leader>bk', function() MiniBufremove.delete(0) end, { desc = 'Kill buffer' })
vim.keymap.set('', '<leader>bK', '<CMD>%bd<CR>', { desc = 'Kill all buffers' })
vim.keymap.set('', '<leader>bf', function() require('fzf-lua').buffers() end, { desc = 'Find buffer' })
vim.keymap.set('', 'gt', function() MiniBracketed.buffer('forward') end, {})
vim.keymap.set('', 'gT', function() MiniBracketed.buffer('backward') end, {})
vim.keymap.set('', '<leader>w', '', { desc = 'Window' })
vim.keymap.set('', '<leader>wv', '<CMD>vsplit<CR>', { desc = 'Vertical split' })
vim.keymap.set('', '<leader>wh', '<CMD>split<CR>', { desc = 'Horizontal split' })
vim.keymap.set('', '<leader>wc', '<CMD>q<CR>', { desc = 'Close window' })
vim.keymap.set('', '<leader>w<up>', '<CMD>wincmd k<CR>', { desc = 'Select window up' })
vim.keymap.set('', '<leader>w<down>', '<CMD>wincmd j<CR>', { desc = 'Select window down' })
vim.keymap.set('', '<leader>w<left>', '<CMD>wincmd h<CR>', { desc = 'Select window left' })
vim.keymap.set('', '<leader>w<right>', '<CMD>wincmd l<CR>', { desc = 'Select window right' })
vim.keymap.set('', '<leader>o', '', { desc = 'Open' })
vim.keymap.set('', '<leader>op', function() MiniFiles.open(vim.api.nvim_buf_get_name(0)) end, { desc = 'Open file browser at current file' })
vim.keymap.set('', '<leader>of', function() MiniFiles.open() end, { desc = 'Open file browser at root' })
vim.keymap.set('', '<leader>g', '', { desc = 'Git' })
vim.keymap.set('', '<leader>gg', '<CMD>Git<CR>', { desc = 'Open Fugitive' })
vim.keymap.set('', 'gd', function() vim.lsp.buf.definition() end, {})
vim.keymap.set('', 'gD', function() vim.lsp.buf.references() end, {})
vim.keymap.set('', 'gi', function() vim.lsp.buf.implementation() end, {})
vim.keymap.set('', '<leader>ca', function() vim.lsp.buf.code_action() end, {})

